name: nsp3
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - absl-py=0.12.0=pyhd8ed1ab_0
  - aiohttp=3.7.4=py38h497a2fe_0
  - anyio=2.2.0=py38h578d9bd_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=20.1.0=py38h497a2fe_2
  - astroid=2.5=py38h06a4308_1
  - async-timeout=3.0.1=py_1000
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - autopep8=1.5.6=pyhd8ed1ab_0
  - babel=2.9.0=pyhd3deb0d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - black=20.8b1=py_1
  - bleach=3.3.0=pyh44b312d_0
  - blinker=1.4=py_1
  - brotlipy=0.7.0=py38h497a2fe_1001
  - c-ares=1.17.1=h7f98852_1
  - ca-certificates=2021.1.19=h06a4308_1
  - cachetools=4.2.1=pyhd8ed1ab_0
  - certifi=2020.12.5=py38h06a4308_0
  - cffi=1.14.5=py38ha65f79e_0
  - chardet=4.0.0=py38h578d9bd_1
  - click=7.1.2=pyh9f0ad1d_0
  - cryptography=3.4.6=py38ha5dfef3_0
  - cudatoolkit=10.0.130=hf841e97_8
  - cycler=0.10.0=py_2
  - dataclasses=0.8=pyhc8e2a94_1
  - dbus=1.13.6=hfdff14a_1
  - decorator=4.4.2=py_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.2.10=h9c3ff4c_0
  - flake8=3.9.0=pyhd8ed1ab_0
  - fontconfig=2.13.1=hba837de_1004
  - freetype=2.10.4=h0708190_1
  - future=0.18.2=py38h578d9bd_3
  - gettext=0.19.8.1=h0b5b191_1005
  - glib=2.66.7=h9c3ff4c_1
  - glib-tools=2.66.7=h9c3ff4c_1
  - google-auth=1.24.0=pyhd3deb0d_0
  - google-auth-oauthlib=0.4.1=py_2
  - grpcio=1.36.1=py38hdd6454d_0
  - gst-plugins-base=1.18.4=h29181c9_0
  - gstreamer=1.18.4=h76c114f_0
  - icu=68.1=h58526e2_0
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=3.7.3=py38h578d9bd_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.21.0=py38h81c977d_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.3=pyhd3deb0d_0
  - isort=5.8.0=pyhd3eb1b0_0
  - jedi=0.18.0=py38h578d9bd_2
  - jinja2=2.11.3=pyh44b312d_0
  - jpeg=9d=h36c2ea0_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter=1.0.0=py38h578d9bd_6
  - jupyter-packaging=0.7.12=pyhd8ed1ab_0
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.7.1=py38h578d9bd_0
  - jupyter_server=1.4.1=py38h578d9bd_0
  - jupyterlab=3.0.12=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.3.0=pyhd8ed1ab_0
  - jupyterlab_widgets=1.0.0=pyhd8ed1ab_1
  - kiwisolver=1.3.1=py38h1fd1430_1
  - krb5=1.17.2=h926e7f8_0
  - lazy-object-proxy=1.6.0=py38h27cfd23_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - libblas=3.9.0=8_openblas
  - libcblas=3.9.0=8_openblas
  - libclang=11.1.0=default_ha53f305_0
  - libedit=3.1.20191231=he28a2e2_2
  - libevent=2.1.10=hcdb4288_3
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_18
  - libgfortran-ng=9.3.0=hff62375_18
  - libgfortran5=9.3.0=hff62375_18
  - libglib=2.66.7=h3e27bee_1
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=8_openblas
  - libllvm11=11.1.0=hf817b99_0
  - libopenblas=0.3.12=pthreads_h4812303_1
  - libpng=1.6.37=h21135ba_2
  - libpq=13.1=hfd2b0eb_2
  - libprotobuf=3.15.6=h780b84a_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=9.3.0=h6de172a_18
  - libtiff=4.2.0=hdc55705_0
  - libuuid=2.32.1=h7f98852_1000
  - libwebp-base=1.2.0=h7f98852_1
  - libxcb=1.13=h7f98852_1003
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.10=h72842e0_3
  - llvm-openmp=11.0.1=h4bd325d_0
  - lz4-c=1.9.3=h9c3ff4c_0
  - markdown=3.3.4=pyhd8ed1ab_0
  - markupsafe=1.1.1=py38h497a2fe_3
  - matplotlib=3.3.4=py38h578d9bd_0
  - matplotlib-base=3.3.4=py38h0efea84_0
  - mccabe=0.6.1=py_1
  - mistune=0.8.4=py38h497a2fe_1003
  - mkl=2020.4=h726a3e6_304
  - more-itertools=8.7.0=pyhd8ed1ab_0
  - multidict=5.1.0=py38h497a2fe_1
  - mypy_extensions=0.4.3=py38h578d9bd_3
  - mysql-common=8.0.23=ha770c72_1
  - mysql-libs=8.0.23=h935591d_1
  - nbclassic=0.2.6=pyhd8ed1ab_0
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.0.7=py38h578d9bd_3
  - nbformat=5.1.2=pyhd8ed1ab_1
  - ncurses=6.2=h58526e2_4
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - ninja=1.10.2=h4bd325d_0
  - notebook=6.2.0=py38h578d9bd_0
  - nspr=4.29=h9c3ff4c_1
  - nss=3.62=hb5efdd6_0
  - numpy=1.20.1=py38h18fd61f_0
  - oauthlib=3.0.1=py_0
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.1.1k=h27cfd23_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.2.3=py38h51da96c_0
  - pandoc=2.12=h7f98852_0
  - pandocfilters=1.4.2=py_1
  - parso=0.8.1=pyhd8ed1ab_0
  - pathspec=0.8.1=pyhd3deb0d_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.1.2=py38ha0e1e83_0
  - pip=21.0.1=pyhd8ed1ab_0
  - pluggy=0.13.1=py38h578d9bd_4
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt-toolkit=3.0.17=pyha770c72_0
  - prompt_toolkit=3.0.17=hd8ed1ab_0
  - protobuf=3.15.6=py38h709712a_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - py=1.10.0=pyhd3deb0d_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycodestyle=2.7.0=pyhd8ed1ab_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyflakes=2.3.0=pyhd8ed1ab_0
  - pygments=2.8.1=pyhd8ed1ab_0
  - pyjwt=2.0.1=pyhd8ed1ab_0
  - pylint=2.7.2=py38h06a4308_1
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py38h578d9bd_7
  - pyqt-impl=5.12.3=py38h7400c14_7
  - pyqt5-sip=4.19.18=py38h709712a_7
  - pyqtchart=5.12=py38h7400c14_7
  - pyqtwebengine=5.12.1=py38h7400c14_7
  - pyrsistent=0.17.3=py38h497a2fe_2
  - pysocks=1.7.1=py38h578d9bd_3
  - pytest=6.2.2=py38h578d9bd_0
  - python=3.8.8=hffdb5ce_0_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2021.1=pyhd8ed1ab_0
  - pyyaml=5.4.1=py38h497a2fe_0
  - pyzmq=22.0.3=py38h2035c66_1
  - qt=5.12.9=hda022c4_4
  - qtconsole=5.0.2=pyhd8ed1ab_0
  - qtpy=1.9.0=py_0
  - readline=8.0=he28a2e2_2
  - regex=2020.11.13=py38h497a2fe_1
  - requests=2.25.1=pyhd3deb0d_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rope=0.18.0=pyh9f0ad1d_0
  - rsa=4.7.2=pyh44b312d_0
  - scipy=1.6.0=py38hb2138dd_0
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py38h578d9bd_3
  - six=1.15.0=pyh9f0ad1d_0
  - sniffio=1.2.0=py38h578d9bd_1
  - sqlite=3.34.0=h74cdb3f_0
  - tensorboard=2.4.1=pyhd8ed1ab_0
  - tensorboard-plugin-wit=1.8.0=pyh44b312d_0
  - terminado=0.9.2=py38h578d9bd_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=h21135ba_1
  - toml=0.10.2=pyhd8ed1ab_0
  - tornado=6.1=py38h497a2fe_1
  - tqdm=4.59.0=pyhd8ed1ab_0
  - traitlets=5.0.5=py_0
  - typed-ast=1.4.2=py38h497a2fe_0
  - typing-extensions=3.7.4.3=0
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.26.4=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.36.2=pyhd3deb0d_0
  - widgetsnbextension=3.5.1=py38h578d9bd_4
  - wrapt=1.12.1=py38h7b6447c_1
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - yarl=1.6.3=py38h497a2fe_1
  - zeromq=4.3.4=h9c3ff4c_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.9=ha95c52a_0
  - pip:
    - data==0.4
    - fair-esm==0.3.1
    - funcsigs==1.0.2
    - h5py==3.2.1
    - latex==0.7.0
    - scienceplots==1.0.7
    - shutilwhich==1.1.0
    - tempdir==0.7.1
    - torch==1.8.0
    - torchvision==0.9.0
prefix: /home/eryk/anaconda3/envs/nsp3
