name: nsp3
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=0.12.0
  - aiohttp=3.7.4
  - alembic=1.6.5
  - anyio=2.2.0
  - appdirs=1.4.4
  - argon2-cffi=20.1.0
  - astroid=2.5
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=20.3.0
  - autopep8=1.5.6
  - babel=2.9.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - black=20.8b1
  - bleach=3.3.0
  - blinker=1.4
  - brotlipy=0.7.0
  - c-ares=1.17.1
  - ca-certificates=2021.5.30
  - cachetools=4.2.1
  - certifi=2021.5.30
  - cffi=1.14.5
  - click=7.1.2
  - cliff=3.8.0
  - cmaes=0.8.2
  - cmd2=2.1.1
  - colorama=0.4.4
  - colorlog=5.0.1
  - cryptography=3.4.6
  - cudatoolkit=10.0.130
  - cycler=0.10.0
  - dataclasses=0.8
  - dbus=1.13.6
  - decorator=4.4.2
  - defusedxml=0.7.1
  - entrypoints=0.3
  - expat=2.2.10
  - flake8=3.9.0
  - fontconfig=2.13.1
  - freetype=2.10.4
  - future=0.18.2
  - gettext=0.19.8.1
  - glib=2.66.7
  - glib-tools=2.66.7
  - google-auth=1.24.0
  - google-auth-oauthlib=0.4.1
  - greenlet=1.1.0
  - grpcio=1.36.1
  - gst-plugins-base=1.18.4
  - gstreamer=1.18.4
  - icu=68.1
  - idna=2.10
  - importlib-metadata=3.7.3
  - iniconfig=1.1.1
  - ipykernel=5.3.4
  - ipython=7.21.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - isort=5.8.0
  - jedi=0.18.0
  - jinja2=2.11.3
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter-packaging=0.7.12
  - jupyter_client=6.1.12
  - jupyter_console=6.2.0
  - jupyter_core=4.7.1
  - jupyter_server=1.4.1
  - jupyterlab=3.0.12
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.3.0
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.66.7
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libpq=13.1
  - libprotobuf=3.15.6
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=2.32.1
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.10
  - llvm-openmp=11.0.1
  - lz4-c=1.9.3
  - mako=1.1.4
  - markdown=3.3.4
  - markupsafe=1.1.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2020.4
  - more-itertools=8.7.0
  - multidict=5.1.0
  - mypy_extensions=0.4.3
  - mysql-common=8.0.23
  - mysql-libs=8.0.23
  - nbclassic=0.2.6
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - ncurses=6.2
  - ninja=1.10.2
  - notebook=6.2.0
  - nspr=4.29
  - nss=3.62
  - numpy=1.20.1
  - oauthlib=3.0.1
  - olefile=0.46
  - openssl=1.1.1k
  - optuna=2.8.0
  - packaging=20.9
  - pandas=1.2.3
  - pandoc=2.12
  - pandocfilters=1.4.2
  - parso=0.8.1
  - pathspec=0.8.1
  - pbr=5.6.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.1.2
  - pip=21.0.1
  - pluggy=0.13.1
  - prettytable=2.1.0
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.17
  - prompt_toolkit=3.0.17
  - protobuf=3.15.6
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - py=1.10.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycodestyle=2.7.0
  - pycparser=2.20
  - pyflakes=2.3.0
  - pygments=2.8.1
  - pyjwt=2.0.1
  - pylint=2.7.2
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyperclip=1.8.2
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pytest=6.2.2
  - python=3.8.8
  - python-dateutil=2.8.1
  - python-editor=1.0.4
  - python_abi=3.8
  - pytz=2021.1
  - pyyaml=5.4.1
  - pyzmq=22.0.3
  - qt=5.12.9
  - qtconsole=5.0.2
  - qtpy=1.9.0
  - readline=8.0
  - regex=2020.11.13
  - requests-oauthlib=1.3.0
  - rope=0.18.0
  - rsa=4.7.2
  - scipy=1.6.0
  - send2trash=1.5.0
  - setuptools=49.6.0
  - six=1.15.0
  - sniffio=1.2.0
  - sqlalchemy=1.4.18
  - sqlite=3.34.0
  - stevedore=3.3.0
  - tensorboard=2.4.1
  - tensorboard-plugin-wit=1.8.0
  - terminado=0.9.2
  - testpath=0.4.4
  - tk=8.6.10
  - toml=0.10.2
  - tornado=6.1
  - tqdm=4.59.0
  - traitlets=5.0.5
  - typed-ast=1.4.2
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zeromq=4.3.4
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - aenum==2.2.6
    - biopython==1.78
    - boto3==1.16.53
    - botocore==1.19.63
    - chardet==3.0.4
    - data==0.4
    - docker==4.4.1
    - fair-esm==0.3.1
    - flask==1.1.2
    - flask-cors==3.0.10
    - funcsigs==1.0.2
    - gunicorn==19.9.0
    - h5py==3.2.1
    - importlib==1.0.4
    - install==1.3.4
    - itsdangerous==1.1.0
    - jmespath==0.10.0
    - joblib==1.0.1
    - latex==0.7.0
    - mpld3==0.5.2
    - nest-asyncio==1.4.0
    - ordered-set==4.0.2
    - pybiolib==0.2.116
    - pycryptodome==3.9.9
    - pyee==7.0.4
    - requests==2.24.0
    - s3transfer==0.3.6
    - scienceplots==1.0.7
    - scikit-learn==0.24.2
    - shutilwhich==1.1.0
    - sklearn==0.0
    - tempdir==0.7.1
    - threadpoolctl==2.1.0
    - torch==1.8.0
    - torchvision==0.9.0
    - urllib3==1.25.11
    - websocket-client==0.58.0
    - websockets==8.1
